/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pia.componentes;

import javax.swing.JButton;

/**
 *
 * @author Arturo A. Calcaneo B
 */
public class PanelHabitacion extends javax.swing.JPanel {
    
    private int CLAVE_CATHAB;

    /**
     * Creates new form PanelHabitacion
     */
    public PanelHabitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHabitacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        costodeHabitacion = new javax.swing.JLabel();
        tituloHabitacion = new javax.swing.JLabel();
        asignarHuesped = new javax.swing.JButton();
        verHabitacion = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        panelHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        panelHabitacion.setLayout(new java.awt.GridLayout(0, 2));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/61e3c3c05bcb040e124cb5c93c9d0968.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        panelHabitacion.add(jLabel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        costodeHabitacion.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        costodeHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        costodeHabitacion.setText("0.00");
        jPanel1.add(costodeHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 240, 20));

        tituloHabitacion.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
        tituloHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        tituloHabitacion.setText("Junior Suite");
        jPanel1.add(tituloHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 20));

        asignarHuesped.setBackground(new java.awt.Color(0, 153, 204));
        asignarHuesped.setForeground(new java.awt.Color(255, 255, 255));
        asignarHuesped.setText("Reservar Habitación");
        jPanel1.add(asignarHuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, 40));

        verHabitacion.setBackground(new java.awt.Color(255, 255, 0));
        verHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        verHabitacion.setText("Ver habitación");
        jPanel1.add(verHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 40));

        panelHabitacion.add(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private int getCLAVE_CATHAB() {
        return CLAVE_CATHAB;
    }

    public void setCLAVE_CATHAB(int CLAVE_CATHAB) {
        this.CLAVE_CATHAB = CLAVE_CATHAB;
    }

    public void setTITULO(String TITULO) {
        this.tituloHabitacion.setText(TITULO);
    }

    public void setPRECIO(float PRECIO) {
        this.costodeHabitacion.setText( "$ " + String.valueOf(PRECIO) );
    }

    public JButton getAsignarHuesped() {
        return asignarHuesped;
    }

    public void setAsignarHuesped(JButton asignarHuesped) {
        this.asignarHuesped = asignarHuesped;
    }

    public JButton getVerHabitacion() {
        return verHabitacion;
    }

    public void setVerHabitacion(JButton verHabitacion) {
        this.verHabitacion = verHabitacion;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarHuesped;
    private javax.swing.JLabel costodeHabitacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelHabitacion;
    private javax.swing.JLabel tituloHabitacion;
    private javax.swing.JButton verHabitacion;
    // End of variables declaration//GEN-END:variables
}
