package pia;

import java.awt.EventQueue;
import javax.swing.JOptionPane;
import modelos.Habitaciones;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class VerHabitacion extends javax.swing.JFrame {
    
    // Esta variable almacenara todos los datos de la habitación seleccionada desde Habitaciones.class
    private modelos.Habitaciones infoHabitacion= new modelos.Habitaciones();

    /**
     * Creates new form Habitaciones
     */
    public VerHabitacion() {
        initComponents();
        setTitle("Hoteleria | Habitación");
        setResizable(false);
        this.setLocationRelativeTo(null);
        
        this.btnModificarHabitacion.setEnabled(false);
        this.btnEliminarHabitacion.setEnabled(false);
        this.btnReservar.setEnabled(false);
        
        EventQueue.invokeLater(() -> {
            cargarPreviewDeDatos();
            
            this.btnModificarHabitacion.setEnabled(true);
            this.btnEliminarHabitacion.setEnabled(true);
            this.btnReservar.setEnabled(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tituloHabitacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imgHabitacion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        precioHabitacion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pisoHabitacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        habitacionDesc = new javax.swing.JTextArea();
        btnReservar = new javax.swing.JButton();
        btnModificarHabitacion = new javax.swing.JButton();
        btnEliminarHabitacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        tituloHabitacion.setFont(new java.awt.Font("Source Sans Pro Black", 3, 22)); // NOI18N
        tituloHabitacion.setText("Suite Master");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(tituloHabitacion)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tituloHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 610, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/d1a1237d6058b3f65990840d00284fcf.jpg"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 580, 78));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        imgHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imgHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/preview_habitacion.jpg"))); // NOI18N
        jPanel2.add(imgHabitacion, new java.awt.GridBagConstraints());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 2, 12, 12));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0, 10, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Precio:");
        jPanel3.add(jLabel1);

        precioHabitacion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        precioHabitacion.setForeground(new java.awt.Color(51, 51, 51));
        precioHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(precioHabitacion);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Piso:");
        jPanel3.add(jLabel4);

        pisoHabitacion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pisoHabitacion.setForeground(new java.awt.Color(51, 51, 51));
        pisoHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(pisoHabitacion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel2.add(jPanel3, gridBagConstraints);

        habitacionDesc.setBackground(new java.awt.Color(255, 255, 51));
        habitacionDesc.setColumns(20);
        habitacionDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        habitacionDesc.setRows(5);
        jScrollPane1.setViewportView(habitacionDesc);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 560, 580));

        btnReservar.setBackground(new java.awt.Color(0, 153, 204));
        btnReservar.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar.setText("Reservar Habitación");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        bg.add(btnReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 150, 70));

        btnModificarHabitacion.setBackground(new java.awt.Color(0, 51, 255));
        btnModificarHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarHabitacion.setText("Modificar");
        btnModificarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarHabitacionActionPerformed(evt);
            }
        });
        bg.add(btnModificarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 150, 40));

        btnEliminarHabitacion.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminarHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarHabitacion.setText("Eliminar");
        btnEliminarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHabitacionActionPerformed(evt);
            }
        });
        bg.add(btnEliminarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarPreviewDeDatos(){
        this.tituloHabitacion.setText( this.infoHabitacion.getTIPO_HABIT() );
        
        this.habitacionDesc.setText( this.infoHabitacion.getTIPO_HABIT_OTRO_DESCRIPCION() );
        this.habitacionDesc.setEditable(false);
        
        this.precioHabitacion.setText( String.valueOf( this.infoHabitacion.getPRECIO() ) );
        
        this.pisoHabitacion.setText( String.valueOf( this.infoHabitacion.getPISO() ) );
    }
    
    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        Reservacion reserv= new Reservacion();
        reserv.setVisible(true);
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnModificarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarHabitacionActionPerformed
        AlterarDatosHabitacion modificarHabitacion_VirtualView= new AlterarDatosHabitacion();
        
        modificarHabitacion_VirtualView.setInfoHabitacion( this.infoHabitacion );
        
        modificarHabitacion_VirtualView.getBtnGuardar().setBackground(new java.awt.Color(0,153,255));
        modificarHabitacion_VirtualView.getBtnGuardar().setText("Guardar Cambios");
        
        modificarHabitacion_VirtualView.setVisible(true);
        
        // El mecanismo de actualización funciona en RegistroHabitacion.java
    }//GEN-LAST:event_btnModificarHabitacionActionPerformed

    private void btnEliminarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHabitacionActionPerformed
        var respuesta= JOptionPane.showConfirmDialog(this.jPanel2, "¿Seguro que desea proceder con la eliminación?", "Ver Habitación | Eliminar", JOptionPane.OK_CANCEL_OPTION);
        if(respuesta == 0){
            if( this.infoHabitacion.eliminarHabitacion() ){
                JOptionPane.showMessageDialog(this.jPanel2, "La habitación ha sido eliminada con éxito.", "Ver Habitación | Eliminar", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnEliminarHabitacionActionPerformed

    public Habitaciones getInfoHabitacion() {
        return infoHabitacion;
    }

    public void setInfoHabitacion(Habitaciones infoHabitacion) {
        this.infoHabitacion = infoHabitacion;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnEliminarHabitacion;
    private javax.swing.JButton btnModificarHabitacion;
    private javax.swing.JButton btnReservar;
    private javax.swing.JTextArea habitacionDesc;
    private javax.swing.JLabel imgHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pisoHabitacion;
    private javax.swing.JLabel precioHabitacion;
    private javax.swing.JLabel tituloHabitacion;
    // End of variables declaration//GEN-END:variables
}
