package pia;

import modelos.Habitaciones;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class VerHabitacion extends javax.swing.JFrame {
    
    private modelos.Habitaciones infoHabitacion= new modelos.Habitaciones();

    /**
     * Creates new form Habitaciones
     */
    public VerHabitacion() {
        initComponents();
        setTitle("Hoteleria | Habitación");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnReservar = new javax.swing.JButton();
        btnModificarHabitacion = new javax.swing.JButton();
        btnEliminarHabitacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 3, 20)); // NOI18N
        jLabel1.setText("Suite Master");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel1)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 610, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/d1a1237d6058b3f65990840d00284fcf.jpg"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 580, 78));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/preview_habitacion.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        jTextArea1.setBackground(new java.awt.Color(255, 255, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Tipo de cama:\n2 habitaciones (1 habitación con cama king size y otra con 2 camas matrimoniales).\n\nCaracterísticas:\nSuite de 195 m²2\n\nBeneficios:\nAcceso a la terraza con camastros y jacuzzi exterior.\nDescripción: aire acondicionado, sala, comedor, escritorio, silla ejecutiva y kit de planchado.\n\nDetalles de la habitación\n\nServicios: caja de seguridad y minibar.\nComunicación: línea telefónica y 2 televisiones de 32\" y de 55\" con servicio de señal satelital.\nBaño: 1 Habitación cuenta con baño completo y la otra habitacion baño completo con tina de hidromasaje, secadora, espejo de vanidad, amenidades de lujo, bata de baño, pantuflas y kit de higiene personal.\nSeguridad: sistema contra incendios con detectores de humo y aspersores.\nEntradas y salidas: registro de entrada 15:00 h, registro de salida 13:00 h.\nExtras: camas con costo adicional y cunas gratuitas sujetas a disponibilidad.\n");
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 560, 580));

        btnReservar.setBackground(new java.awt.Color(0, 153, 204));
        btnReservar.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar.setText("Reservar Habitación");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        bg.add(btnReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 150, 70));

        btnModificarHabitacion.setBackground(new java.awt.Color(0, 51, 255));
        btnModificarHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarHabitacion.setText("Modificar");
        btnModificarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarHabitacionActionPerformed(evt);
            }
        });
        bg.add(btnModificarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, 150, 40));

        btnEliminarHabitacion.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminarHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarHabitacion.setText("Eliminar");
        btnEliminarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHabitacionActionPerformed(evt);
            }
        });
        bg.add(btnEliminarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnModificarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarHabitacionActionPerformed
        RegistroHabitacion modificarVirtual= new RegistroHabitacion();
        modificarVirtual.setCLAVE_CATHAB_AUX_TOMODIFY( this.infoHabitacion.getCLAVE_CATHAB() );
        modificarVirtual.getBtnGuardar().setText("Guardar Cambios");
        
        modificarVirtual.setVisible(true);
        
        // El mecanismo de actualización funciona en RegistroHabitacion.java
    }//GEN-LAST:event_btnModificarHabitacionActionPerformed

    private void btnEliminarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHabitacionActionPerformed
        this.infoHabitacion.eliminarHabitacion();
    }//GEN-LAST:event_btnEliminarHabitacionActionPerformed

    public Habitaciones getInfoHabitacion() {
        return infoHabitacion;
    }

    public void setInfoHabitacion(Habitaciones infoHabitacion) {
        this.infoHabitacion = infoHabitacion;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnEliminarHabitacion;
    private javax.swing.JButton btnModificarHabitacion;
    private javax.swing.JButton btnReservar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
